#pragma once
/* Gerado por tools/gen_asset_ids.py — NAO EDITE A MAO.
 * Fonte: assets/asset_registry.json
 * Os valores casam com o campo 'id' do registry e com o manifest do
 * asset_store. Use com asset_loader_load(ASSET_TYPE_*, ASSET_*, ...). */

/* categoria: sprite */
enum {
    ASSET_REC_PISO              = 0,
    ASSET_REC_BANCO_P           = 1,
    ASSET_REC_BEBEDOURO         = 2,
    ASSET_REC_CADEIRA_ESQ       = 3,
    ASSET_REC_CADEIRA_COSTA     = 4,
    ASSET_REC_CADEIRA_DIR       = 5,
    ASSET_REC_CADEIRA_FRT       = 6,
    ASSET_REC_MESA_L            = 7,
    ASSET_REC_MESA_CENTRO       = 8,
    ASSET_REC_SOFA              = 9,
    ASSET_REC_PLANTA            = 10,
    ASSET_REC_PAREDE_01         = 11,
    ASSET_REC_PAREDE_02         = 12,
    ASSET_REC_LIXEIRA           = 13,
    ASSET_REC_NPC_01_IDLE       = 14,
    ASSET_REC_NPC_01_DIALOG     = 15,
    ASSET_REC_ICONE_NOTIF       = 16,
    ASSET_REC_RECEP_DIALOG_FULL = 17,
    ASSET_REC_CAIXA_DIALOGO     = 18,
    ASSET_REC_CAIXA_TEXTO       = 19,
    ASSET_EMP_PISO              = 20,
    ASSET_EMP_IMPRESSORA        = 21,
    ASSET_EMP_CAFETEIRA         = 22,
    ASSET_EMP_PLANTA_02         = 23,
    ASSET_EMP_MESA_L_01         = 24,
    ASSET_EMP_MESA_L_02         = 25,
    ASSET_EMP_CADEIRA_ESQ       = 26,
    ASSET_EMP_CADEIRA_COSTA     = 27,
    ASSET_PLAYER                = 28,
    ASSET_REC_DIALOG            = 29,
    ASSET_EMP_PAREDE_03         = 30,
    ASSET_EMP_PAREDE_04         = 31,
    ASSET_EMP_PAREDE_05         = 32,
    ASSET_EMP_PAREDE_06         = 33,
    ASSET_EMP_PAREDE_07         = 34,
    ASSET_EMP_SERVIDOR          = 35,
    ASSET_EMP_NPC_02_IDLE       = 36,
    ASSET_EMP_NPC_02_DIALOG     = 37,
    ASSET_EMP_NPC_03_IDLE       = 38,
    ASSET_EMP_ICONE_VERDE       = 39,
    ASSET_EMP_ICONE_AMARELO     = 40,
};
